//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 

namespace TimeLineTestApp
{
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class PaymentData
	{

		private PaymentDataHolydays holydaysField;

		private PaymentDataDate[] preHolydaysField;

		private PaymentDataSalary[] salariesField;

		private PaymentDataShedule[] shedulesField;

		private PaymentDataPeriod[] workField;

		[System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "year", DataType = "int")]
		public int Year { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "month", DataType = "int")]
		public int Month { get; set; }

		/// <remarks/>
		public PaymentDataHolydays Holydays
		{
			get
			{
				return this.holydaysField;
			}
			set
			{
				this.holydaysField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("Date", IsNullable = false)]
		public PaymentDataDate[] PreHolydays
		{
			get
			{
				return this.preHolydaysField;
			}
			set
			{
				this.preHolydaysField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayItemAttribute("Salary", IsNullable = false)]
		public PaymentDataSalary[] Salaries
		{
			get
			{
				return this.salariesField;
			}
			set
			{
				this.salariesField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayItemAttribute("Shedule", IsNullable = false)]
		public PaymentDataShedule[] Shedules
		{
			get
			{
				return this.shedulesField;
			}
			set
			{
				this.shedulesField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayItemAttribute("Period", IsNullable = false)]
		public PaymentDataPeriod[] Work
		{
			get
			{
				return this.workField;
			}
			set
			{
				this.workField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PaymentDataHolydays
	{

		private PaymentDataHolydaysHolyday[] holydayField;

		private System.DateTime beginField;

		private System.DateTime endField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("Holyday")]
		public PaymentDataHolydaysHolyday[] Holyday
		{
			get
			{
				return this.holydayField;
			}
			set
			{
				this.holydayField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
		public System.DateTime begin
		{
			get
			{
				return this.beginField;
			}
			set
			{
				this.beginField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
		public System.DateTime end
		{
			get
			{
				return this.endField;
			}
			set
			{
				this.endField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PaymentDataHolydaysHolyday
	{

		private System.DateTime beginField;

		private System.DateTime endField;

		private bool endFieldSpecified;

		private string descriptionField;

		private System.DateTime transferFromField;

		private bool transferFromFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
		public System.DateTime begin
		{
			get
			{
				return this.beginField;
			}
			set
			{
				this.beginField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
		public System.DateTime end
		{
			get
			{
				return this.endField;
			}
			set
			{
				this.endField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool endSpecified
		{
			get
			{
				return this.endFieldSpecified;
			}
			set
			{
				this.endFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string description
		{
			get
			{
				return this.descriptionField;
			}
			set
			{
				this.descriptionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
		public System.DateTime transferFrom
		{
			get
			{
				return this.transferFromField;
			}
			set
			{
				this.transferFromField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool transferFromSpecified
		{
			get
			{
				return this.transferFromFieldSpecified;
			}
			set
			{
				this.transferFromFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PaymentDataDate
	{

		private System.DateTime valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
		public System.DateTime value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PaymentDataPeriod
	{
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
		public System.DateTime begin { get; set; }

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool beginSpecified { get; set; }

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "time")]
		public System.DateTime beginTime { get; set; }

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool beginTimeSpecified { get; set; }

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
		public System.DateTime end { get; set; }

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool endSpecified { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "time")]
		public System.DateTime endTime { get; set; }

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool endTimeSpecified { get; set; }
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PaymentDataSalary : PaymentDataPeriod
	{
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "decimal")]
		public System.Decimal value { get; set; }
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class PaymentDataShedule : PaymentDataPeriod
	{
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "int")]
		public int code { get; set; }
	}
}